name: Deploy on fly.io [DEV]
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+_d'
jobs:
  deploy:
    name: Deploy proxy
    runs-on: ubuntu-latest
    steps:
      # check out repository and flyctl deploy
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --app chat-db-migration-dev
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
